spring:
  datasource:
    url: jdbc:mysql:///device_manager?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    username: root
    password: ENC(KV+OuaEiZx5AG3/24nzcoA==)
logging:
  file: /log/service.log